title: Voeg een geordende lijst met genummerde items toe
hero_image: images/banner.png
description: Voeg een geordende lijst met genummerde items toe.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Voeg een geordende lijst toe

