title: Add an ordered list with numbered items
hero_image: images/banner.png
description: Add an ordered list with numbered items. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Add an ordered list

